import '@mantine/core/styles.css';
import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import { Navbar } from '@/components/navbar';
import { ModalsProvider } from '@mantine/modals';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Lumisca',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${inter.className} min-h-svh flex flex-col`}>
        <MantineProvider>
          <ModalsProvider
            modalProps={{
              classNames: {
                title: 'text-zinc-700 font-semibold',
              },
            }}
          >
            <Navbar />

            {children}
          </ModalsProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
